name: Q41 Fixed M3U Generator
version: "1.0.0"
slug: q41_fixed_m3u
description: Generate fixed Q41 M3U playlist
startup: once
boot: auto
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
